In [3]:
# The code was removed by Watson Studio for sharing.

In [2]:
import numpy as np
import pandas as pd

from sklearn import preprocessing

In [4]:
# The code was removed by Watson Studio for sharing.

Customer_ID     Sex  Earnings Region_Code Marital Status State_of_Origin  \
0   Customer_434  Female     97134    Suburban         Single            Kano   
1  Customer_4641  Female     53754    Suburban        Married           Abuja   
2  Customer_4952  Female     25804    Suburban       Divorced           Lagos   
3  Customer_1489  Female         0    Suburban         Single             Imo   
4   Customer_812    Male    140494       Rural         Single             Imo   

   Customer_Worth  Customer_Reply    Plan Certification Effective To Date  \
0     5017.009472      Interested  Silver  First_Degree          3/2/2011   
1     5151.301306  Not_interested  Silver  First_Degree           1/22/11   
2     4906.894731      Interested  Silver           HND           2/14/11   
3     8512.525936  Not_interested  Silver           HND          8/1/2011   
4     3280.531880  Not_interested  Silver           PHD           2/19/11   

  Status_of_Employment  Premium_Auto_per_Month  Total Claim Amount  \
0       Fully_Employed                     260          624.000000   
1       Fully_Employed                     262          628.800000   
2        In_Retirement                     278          667.200000   
3         Not_employed                     242          871.200000   
4       Fully_Employed                     166          141.799422   

   Vehicle Class Vehicle Size  Months Since Last Claim  \
0            SUV      Medsize                       12   
1            SUV        Small                        5   
2     Sports Car      Medsize                        3   
3     Sports Car      Medsize                        5   
4  Four-Door Car      Medsize                       13   

   Months Since Policy Inception  Counts_of_Open_Complaints  No_Of_POlicy  \
0                             15                          0             1   
1                              2                          0             1   
2                             51                          0             1   
3                             94                          0             8   
4                             19                          2             1   

  kind_of_policy Active_Policy Sales Channel  Best_Offer  
0      Corporate          C_L2         Agent           1  
1       Personal          P_L2         Agent           3  
2       Personal          P_L3         Agent           0  
3       Personal          P_L2        Branch           1  
4       Personal          P_L2   Call Center           3

# VIBR2 PREPARATION (START)

In [11]:
vibr2 = vibr[['Marital Status', 'Customer_Worth', 'Customer_Reply', 'Status_of_Employment','No_Of_POlicy','Sales Channel']]
vibr2.head()

Marital Status  Customer_Worth  Customer_Reply Status_of_Employment  \
0         Single     5017.009472      Interested       Fully_Employed   
1        Married     5151.301306  Not_interested       Fully_Employed   
2       Divorced     4906.894731      Interested        In_Retirement   
3         Single     8512.525936  Not_interested         Not_employed   
4         Single     3280.531880  Not_interested       Fully_Employed   

   No_Of_POlicy Sales Channel  
0             1         Agent  
1             1         Agent  
2             1         Agent  
3             8        Branch  
4             1   Call Center

In [12]:
dummy_variable_2 = pd.get_dummies(vibr2["Customer_Reply"])
dummy_variable_1 = pd.get_dummies(vibr2["Marital Status"])
dummy_variable_3 = pd.get_dummies(vibr2["Status_of_Employment"])
dummy_variable_4 = pd.get_dummies(vibr2["Sales Channel"])


In [13]:
vibr2 = pd.concat([vibr2, dummy_variable_1], axis=1)
vibr2 = pd.concat([vibr2, dummy_variable_2], axis=1)
vibr2 = pd.concat([vibr2, dummy_variable_3], axis=1)
vibr2 = pd.concat([vibr2, dummy_variable_4], axis=1)

vibr2.drop("Customer_Reply", axis = 1, inplace=True)
vibr2.drop("Sales Channel", axis = 1, inplace=True)
vibr2.drop("Status_of_Employment", axis = 1, inplace=True)
vibr2.drop("Marital Status", axis = 1, inplace=True)

In [14]:
vibr2.head()

Customer_Worth  No_Of_POlicy  Divorced  Married  Single  Interested  \
0     5017.009472             1         0        0       1           1   
1     5151.301306             1         0        1       0           0   
2     4906.894731             1         1        0       0           1   
3     8512.525936             8         0        0       1           0   
4     3280.531880             1         0        0       1           0   

   Not_interested  Disabled  Fully_Employed  In_Retirement  Not_employed  \
0               0         0               1              0             0   
1               1         0               1              0             0   
2               0         0               0              1             0   
3               1         0               0              0             1   
4               1         0               1              0             0   

   On_Leave  Agent  Branch  Call Center  Web  
0         0      1       0            0    0  
1         0      1       0            0    0  
2         0      1       0            0    0  
3         0      0       1            0    0  
4         0      0       0            1    0

# VIBR2 PREPARATION (END)

# VIBR2 MODELING

In [15]:
X = vibr2.to_numpy()
X[0:2]

array([[5.01700947e+03, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.15130131e+03, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [20]:
y = vibr['Best_Offer'].values
y[0:5]

array([1, 3, 0, 1, 3])

In [19]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:2]

array([[-0.44075639, -0.82790025, -0.42446852, -1.18540789,  1.67356874,
         2.47209116, -2.47209116, -0.21994662,  0.77217529, -0.18201274,
        -0.57391847, -0.22344148,  1.27409079, -0.62190666, -0.49226429,
        -0.41155791],
       [-0.42076609, -0.82790025, -0.42446852,  0.84359148, -0.5975255 ,
        -0.40451583,  0.40451583, -0.21994662,  0.77217529, -0.18201274,
        -0.57391847, -0.22344148,  1.27409079, -0.62190666, -0.49226429,
        -0.41155791]])

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (5114, 16) (5114,)
Test set: (1279, 16) (1279,)


In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
from sklearn import metrics

In [36]:
Ks = 200
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))

for n in range(1,Ks):
    
     
    MyLady = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=MyLady.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

array([0.42220485, 0.45426114, 0.45269742, 0.45191556, 0.45895231,
       0.45660672, 0.45660672, 0.45660672, 0.45582486, 0.455043  ,
       0.46051603, 0.45347928, 0.45191556, 0.45347928, 0.44722439,
       0.44487881, 0.44487881, 0.45035184, 0.45269742, 0.4511337 ,
       0.45660672, 0.45738858, 0.45895231, 0.45191556, 0.45817045,
       0.45191556, 0.45660672, 0.44722439, 0.44566067, 0.44018765,
       0.43393276, 0.43549648, 0.44331509, 0.43784206, 0.44175137,
       0.44331509, 0.44096951, 0.43784206, 0.44018765, 0.44253323,
       0.44331509, 0.43940579, 0.44018765, 0.44331509, 0.43940579,
       0.43627834, 0.4370602 , 0.43002346, 0.43784206, 0.4370602 ,
       0.44018765, 0.44253323, 0.44175137, 0.44175137, 0.44409695,
       0.44018765, 0.44331509, 0.44096951, 0.44253323, 0.43627834,
       0.44175137, 0.43940579, 0.43784206, 0.43862392, 0.43080532,
       0.43236904, 0.43627834, 0.43393276, 0.43627834, 0.43862392,
       0.4331509 , 0.43158718, 0.43080532, 0.43002346, 0.43158

In [37]:
print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1)

The best accuracy was with 0.46051602814698983 with k= 11


In [21]:
k = 79
MyLady = KNeighborsClassifier(n_neighbors = k).fit(X,y)

In [25]:

body = client_02094e32b66a4036b212117f2460105b.get_object(Bucket='dsproject101-donotdelete-pr-ceaqlie47lhea1',Key='test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test = pd.read_csv(body)
test.head()


Customer_ID     Sex  Earnings Region_Code Marital Status State_of_Origin  \
0   Customer_708    Male    149170       Rural        Married           Lagos   
1    Customer_47  Female     46436    Suburban         Single           Abuja   
2  Customer_3995  Female    189806    Suburban        Married           Abuja   
3  Customer_1513  Female    154306       Urban        Married           Lagos   
4  Customer_3686  Female     47538    Suburban       Divorced            Kano   

   Customer_Worth  Customer_Reply    Plan Certification Effective To Date  \
0     4224.631209  Not_interested  Bronze       O_Level           1/17/11   
1     5516.344018  Not_interested  Bronze       O_Level          2/1/2011   
2     3810.122147      Interested  Silver           HND           1/28/11   
3     7916.823110  Not_interested  Silver           HND          9/2/2011   
4     7933.722181  Not_interested  Bronze       O_Level           2/20/11   

  Status_of_Employment  Premium_Auto_per_Month  Total Claim Amount  \
0       Fully_Employed                     212          218.598065   
1       Fully_Employed                     142          447.793440   
2       Fully_Employed                     188          451.200000   
3       Fully_Employed                     198          355.641958   
4             Disabled                     138          470.097411   

   Vehicle Class Vehicle Size  Months Since Last Claim  \
0            SUV      Medsize                        1   
1   Two-Door Car      Medsize                        7   
2   Two-Door Car        Small                        3   
3  Four-Door Car      Medsize                        3   
4  Four-Door Car      Medsize                       18   

   Months Since Policy Inception  Counts_of_Open_Complaints  No_Of_POlicy  \
0                             49                          0             1   
1                             10                          0             4   
2                             38                          0             1   
3                             27                          2             5   
4                             14                          0             2   

  kind_of_policy Active_Policy Sales Channel  
0       Personal          P_L3         Agent  
1       Personal          P_L2         Agent  
2       Personal          P_L3         Agent  
3       Personal          P_L3        Branch  
4       Personal          P_L2        Branch

In [23]:
test1 = test.drop(["Customer_ID"], axis=1)
test1.head()

Sex  Earnings Region_Code Marital Status State_of_Origin  \
0    Male    149170       Rural        Married           Lagos   
1  Female     46436    Suburban         Single           Abuja   
2  Female    189806    Suburban        Married           Abuja   
3  Female    154306       Urban        Married           Lagos   
4  Female     47538    Suburban       Divorced            Kano   

   Customer_Worth  Customer_Reply    Plan Certification Effective To Date  \
0     4224.631209  Not_interested  Bronze       O_Level           1/17/11   
1     5516.344018  Not_interested  Bronze       O_Level          2/1/2011   
2     3810.122147      Interested  Silver           HND           1/28/11   
3     7916.823110  Not_interested  Silver           HND          9/2/2011   
4     7933.722181  Not_interested  Bronze       O_Level           2/20/11   

  Status_of_Employment  Premium_Auto_per_Month  Total Claim Amount  \
0       Fully_Employed                     212          218.598065   
1       Fully_Employed                     142          447.793440   
2       Fully_Employed                     188          451.200000   
3       Fully_Employed                     198          355.641958   
4             Disabled                     138          470.097411   

   Vehicle Class Vehicle Size  Months Since Last Claim  \
0            SUV      Medsize                        1   
1   Two-Door Car      Medsize                        7   
2   Two-Door Car        Small                        3   
3  Four-Door Car      Medsize                        3   
4  Four-Door Car      Medsize                       18   

   Months Since Policy Inception  Counts_of_Open_Complaints  No_Of_POlicy  \
0                             49                          0             1   
1                             10                          0             4   
2                             38                          0             1   
3                             27                          2             5   
4                             14                          0             2   

  kind_of_policy Active_Policy Sales Channel  
0       Personal          P_L3         Agent  
1       Personal          P_L2         Agent  
2       Personal          P_L3         Agent  
3       Personal          P_L3        Branch  
4       Personal          P_L2        Branch

In [26]:
test1 = test[['Marital Status', 'Customer_Worth', 'Customer_Reply', 'Status_of_Employment','No_Of_POlicy','Sales Channel']]
test1.head()

Marital Status  Customer_Worth  Customer_Reply Status_of_Employment  \
0        Married     4224.631209  Not_interested       Fully_Employed   
1         Single     5516.344018  Not_interested       Fully_Employed   
2        Married     3810.122147      Interested       Fully_Employed   
3        Married     7916.823110  Not_interested       Fully_Employed   
4       Divorced     7933.722181  Not_interested             Disabled   

   No_Of_POlicy Sales Channel  
0             1         Agent  
1             4         Agent  
2             1         Agent  
3             5        Branch  
4             2        Branch

In [24]:
dummy_variable4 = pd.get_dummies(test["Sales Channel"])

dummy_variable3 = pd.get_dummies(test["Marital Status"])

dummy_variable2 = pd.get_dummies(test["Status_of_Employment"])

dummy_variable1 = pd.get_dummies(test["Customer_Reply"])

In [27]:
test1 = pd.concat([test1, dummy_variable1], axis=1)
test1 = pd.concat([test1, dummy_variable2], axis=1)
test1 = pd.concat([test1, dummy_variable3], axis=1)
test1 = pd.concat([test1, dummy_variable4], axis=1)

test1.drop("Customer_Reply", axis = 1, inplace=True)
test1.drop("Sales Channel", axis = 1, inplace=True)
test1.drop("Status_of_Employment", axis = 1, inplace=True)
test1.drop("Marital Status", axis = 1, inplace=True)

test1.head()

Customer_Worth  No_Of_POlicy  Interested  Not_interested  Disabled  \
0     4224.631209             1           0               1         0   
1     5516.344018             4           0               1         0   
2     3810.122147             1           1               0         0   
3     7916.823110             5           0               1         0   
4     7933.722181             2           0               1         1   

   Fully_Employed  In_Retirement  Not_employed  On_Leave  Divorced  Married  \
0               1              0             0         0         0        1   
1               1              0             0         0         0        0   
2               1              0             0         0         0        1   
3               1              0             0         0         0        1   
4               0              0             0         0         1        0   

   Single  Agent  Branch  Call Center  Web  
0       0      1       0            0    0  
1       1      1       0            0    0  
2       0      1       0            0    0  
3       0      0       1            0    0  
4       0      0       1            0    0

In [28]:
New_test=MyLady.predict(test1)
New_test

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
Best_offer = pd.DataFrame(New_test)
Best_offer.head()

0
0  0
1  0
2  0
3  0
4  0

In [30]:
NewTest= test[['Customer_ID']]
NewTest = pd.concat([NewTest, Best_offer], axis=1)
NewTest.columns= ['Customer_ID','Best_offer']
NewTest.head()

Customer_ID  Best_offer
0   Customer_708           0
1    Customer_47           0
2  Customer_3995           0
3  Customer_1513           0
4  Customer_3686           0

In [31]:


project.save_data(file_name = "NewTest4.csv",data = NewTest.to_csv(index=False))

{'file_name': 'NewTest4.csv',
 'message': 'File saved to project storage.',
 'bucket_name': 'dsproject101-donotdelete-pr-ceaqlie47lhea1',
 'asset_id': '3fb18623-e732-4228-bea5-1f5d16cd5c80'}